## 05 - Merging Data

This notebook merges the two scrapes from `03 - Cleaning Data` and `04 - Party Votes` into one dataframe.

In [1]:
import pandas as pd

df = pd.read_csv("voteinfo.csv", na_values=['NaN'])
df1 = pd.read_csv("party_votes.csv", na_values=['NaN'])

In [2]:
df['vote_id'] = df['vote_id'].str.replace(r'<NA>', 'nan', regex=True)

In [3]:
df1['vote_id1'] = df1['vote_id']
df1 = df1.drop(['congress_no', 'session','vote_number', 'vote_id'], axis=1)

In [4]:
df2 = pd.concat([df, df1], axis=1)

In [5]:
congress_votes = []

for index, row in df2.iterrows():
    senators = {}
    senators["democrats"] = row.D_yea + row.D_nay + row.D_no_vote
    senators["republicans"] = row.R_yea + row.R_nay + row.R_no_vote
    senators["independents"] = row.I_yea + row.I_nay + row.I_no_vote    
    congress_votes.append(senators)
congress_votes

df3 = pd.DataFrame(congress_votes)

In [6]:
data = pd.concat([df2, df3], axis=1)
cols = list(data.columns.values)

In [9]:
data = data[['name', 
'circuit', 
'confirmation_date', 
'nomination_no',
'congress_no',
'session', 
'democrats',
'republicans', 
'independents', 
'record_vote_number', 
'yea_votes',
'nay_votes', 
'vote_id',
'D_yea',
'D_nay',
'D_no_vote',
'R_yea',
'R_nay',
'R_no_vote',
'I_yea',
'I_nay',
'I_no_vote',
'votes']]

data.head(5)

,name,circuit,confirmation_date,nomination_no,congress_no,session,democrats,republicans,independents,record_vote_number,...,D_yea,D_nay,D_no_vote,R_yea,R_nay,R_no_vote,I_yea,I_nay,I_no_vote,votes
0,Roopali H. Desai,Ninth,2022-08-04,PN2262,117,2,48,50,2,284.0,...,46,0,2,19,29,2,2,0,0,"[['Baldwin (D-WI)', ' Yea'], ['Barrasso (R-WY)..."
1,Florence Y. Pan,District of Columbia,2022-09-20,PN2193,117,2,48,50,2,340.0,...,46,0,2,4,42,4,2,0,0,"[['Baldwin (D-WI)', ' Not Voting'], ['Barrasso..."
2,Sarah A. L. Merriam,Second,2022-09-15,PN2141,117,2,48,50,2,337.0,...,48,0,0,3,44,3,2,0,0,"[['Baldwin (D-WI)', ' Yea'], ['Barrasso (R-WY)..."
3,Lara E. Montecalvo,First,2022-09-14,PN2140,117,2,48,50,2,335.0,...,47,0,1,3,47,0,2,0,0,"[['Baldwin (D-WI)', ' Yea'], ['Barrasso (R-WY)..."
4,Salvador Mendoza Jr,Ninth,2022-09-12,PN1966,117,2,48,50,2,331.0,...,41,0,7,3,40,7,2,0,0,"[['Baldwin (D-WI)', ' Yea'], ['Barrasso (R-WY)..."

In [8]:
data.to_csv("data.csv", index=False)